#include "../base/MountManagerTest.cc"
#include "../base/NodeTest.cc"
#include "../base/PathHandleTest.cc"
#include "../memory/MemFileHandleTest.cc"
#include "../memory/MemNodeTest.cc"
#include "../memory/MemMountTest.cc"
