#include "../base/MountManagerTest.cc"
#include "../base/NodeTest.cc"
#include "../base/PathHandleTest.cc"
#include "../base/FileHandleTest.cc"
#include "../memory/MemNodeTest.cc"
#include "../memory/MemMountTest.cc"
